name: DragonFly BSD Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: DragonFly BSD unit test
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # Note: -race is not supported on dragonfly/amd64
      - name: Test on DragonFly BSD
        uses: vmactions/dragonflybsd-vm@4ab776fa9f914fbea72f13715b451e77e7ef5c41 # v1.3.4
        with:
          usesh: true
          release: "6.4.0"
          mem: 8192
          copyback: false
          prepare: |
            pkg install -y go tor gmake git
          run: |
            git config --global --add safe.directory /home/runner/work/tornago/tornago
            go version
            tor --version
            go mod download
            gmake integration-test
        env:
          TORNAGO_INTEGRATION: "1"
